-- 코드를 입력하세요
SELECT ai.ANIMAL_ID, ai.ANIMAL_TYPE, ai.NAME
FROM ANIMAL_INS AS ai
JOIN (SELECT ANIMAL_ID
     FROM ANIMAL_OUTS
     WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%') ao ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY ai.ANIMAL_ID