SELECT YEAR(os.SALES_DATE) AS YEAR,
       MONTH(os.SALES_DATE) AS MONTH,
       ui.GENDER,
       COUNT(DISTINCT(os.USER_ID)) AS USERS
FROM ONLINE_SALE os

JOIN USER_INFO ui ON ui.USER_ID = os.USER_ID

WHERE ui.GENDER IS NOT NULL

GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), GENDER

ORDER BY YEAR ASC, MONTH ASC, GENDER ASC

# SELECT *
# FROM ONLINE_SALE

