SELECT HALF.FLAVOR
FROM FIRST_HALF HALF

JOIN (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM JULY
      GROUP BY FLAVOR
     ) AS JULY
ON HALF.SHIPMENT_ID = JULY.SHIPMENT_ID

ORDER BY (HALF.TOTAL_ORDER + JULY.TOTAL_ORDER) DESC
LIMIT 3;

# SELECT FLAVOR, TOTAL_ORDER
# FROM JULY