SELECT USER_ID, NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER u

JOIN (SELECT WRITER_ID, PRICE, STATUS
      FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE') b ON u.USER_ID = b.WRITER_ID

GROUP BY u.USER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC