SELECT b.CATEGORY, SUM(s.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS SALES, SALES_DATE
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01'
    GROUP BY BOOK_ID
     ) AS s ON b.BOOK_ID = s.BOOK_ID

GROUP BY b.CATEGORY
ORDER BY b.CATEGORY
